version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/master_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
      - JWT_SECRET=djFvZ0p5QkFZc3lUa2dFRjQ2dzhRb3hrdFhWcDhxTjV3M1ZjbHplbnM
    depends_on:
      - db
    networks:
      - jarvised-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=master_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - jarvised-network

volumes:
  mysql-data:

networks:
  jarvised-network:
